// Generated by scripts/build-site-index.js from src/data and src/i18n. Do not edit.

export const HEADLINE = "AI/ML Engineer — RAG, LLM & Edge ML Systems";

export const ROLES = [
  {
    "role": "AI Solutions Engineer",
    "company": "Georg Schröder Maritime Unternehmensberatung",
    "period": "Jun 2026 to Present",
    "type": "Working Student",
    "summary": "AI/ML engineering for maritime software — LLM/RAG integration, computer vision, and edge deployment"
  },
  {
    "role": "Senior Software Engineer",
    "company": "Novigo Solutions",
    "period": "Jun 2023 to Feb 2025",
    "type": "Full-time",
    "summary": "Built digital onboarding platforms for US-based banks — requirements analysis, API design, Angular/TypeScript front end, and production deployment"
  },
  {
    "role": "Systems Engineer to Senior System Engineer",
    "company": "Infosys",
    "period": "May 2021 to Jun 2023",
    "type": "Full-time",
    "summary": "Progressed from Systems Engineer to Senior System Engineer within Infosys Helix healthcare division"
  },
  {
    "role": "Consultant",
    "company": "Softusvista",
    "period": "Feb 2021 to Mar 2021",
    "type": "Internship",
    "summary": "Agile application development and business communication consulting"
  }
];

export const PROJECTS = [
  {
    "title": "RAG Portfolio Assistant",
    "subtitle": "Retrieval-Augmented Chat Assistant",
    "tech": [
      "Python",
      "FastAPI",
      "Vector Search",
      "Semantic Cache",
      "LLM"
    ]
  },
  {
    "title": "NIFTY 50 Price Forecasting",
    "subtitle": "LSTM & ARIMA Forecasting",
    "tech": [
      "Python",
      "LSTM",
      "ARIMA",
      "Pandas",
      "NumPy"
    ]
  },
  {
    "title": "TinyML Person Recognition",
    "subtitle": "Edge AI on a Microcontroller",
    "tech": [
      "Python",
      "TensorFlow",
      "Keras",
      "INT8 Quantization",
      "TFLite Micro"
    ]
  },
  {
    "title": "SignalDock",
    "subtitle": "MQTT IoT Messaging Platform",
    "tech": [
      "MQTT",
      "Python",
      "Angular",
      "TypeScript",
      "WebSockets"
    ]
  },
  {
    "title": "Barcode Scanner",
    "subtitle": "Computer-Vision Inventory Scanner",
    "tech": [
      "Python",
      "OpenCV",
      "ZBar",
      "SQLite",
      "REST API"
    ]
  },
  {
    "title": "Python Data Projects",
    "subtitle": "Data Science Notebooks",
    "tech": [
      "Python",
      "Jupyter",
      "Pandas",
      "Matplotlib",
      "NumPy"
    ]
  }
];

export const POSTS = [
  {
    "slug": "onnx-ops-without-deps",
    "title": "Reading a model file with nothing installed at all",
    "date": "2026-09-29",
    "series": "Edge AI",
    "part": 4
  },
  {
    "slug": "edgetpu-position-dominates",
    "title": "One layer decides whether your model uses the accelerator at all",
    "date": "2026-09-22",
    "series": "Edge AI",
    "part": 3
  },
  {
    "slug": "4bit-scaling-law",
    "title": "A bigger model at four bits beats a smaller one at eight",
    "date": "2026-09-15",
    "series": "Edge AI",
    "part": 2
  },
  {
    "slug": "edge-pipeline-map",
    "title": "The five steps between a trained model and a device that runs it",
    "date": "2026-09-08",
    "series": "Edge AI",
    "part": 1
  },
  {
    "slug": "lost-in-the-middle",
    "title": "Your retriever found the answer and the model read past it",
    "date": "2026-08-25",
    "series": null,
    "part": null
  },
  {
    "slug": "late-interaction-retrieval-colbert-reranking-rag",
    "title": "Late interaction and reranking: where single-vector RAG falls short",
    "date": "2026-06-22",
    "series": "Production RAG",
    "part": 14
  },
  {
    "slug": "cluster-quality-evaluation-rag-retrieval-metrics",
    "title": "Cluster quality evaluation for RAG: metrics that match retrieval goals",
    "date": "2026-06-15",
    "series": "Production RAG",
    "part": 13
  },
  {
    "slug": "nearest-neighbor-search-flat-ivf-hnsw-rag",
    "title": "Nearest neighbor search in RAG: Flat, IVF and HNSW trade-offs",
    "date": "2026-06-08",
    "series": "Production RAG",
    "part": 12
  },
  {
    "slug": "dimensionality-reduction-pca-umap-rag-clustering",
    "title": "PCA, t-SNE and UMAP: reducing dimensions before clustering for RAG",
    "date": "2026-06-01",
    "series": "Production RAG",
    "part": 11
  },
  {
    "slug": "transformer-embeddings-tokens-vectors-rag-mismatch",
    "title": "Why Embedding Model Mismatch Silently Breaks RAG Systems",
    "date": "2026-05-25",
    "series": "Production RAG",
    "part": 10
  },
  {
    "slug": "dbscan-density-clustering-rag-quality-filter",
    "title": "DBSCAN: density-based clustering as a RAG quality filter",
    "date": "2026-05-18",
    "series": "Production RAG",
    "part": 9
  },
  {
    "slug": "kmeans-centroids-convergence-rag-routing",
    "title": "K-Means clustering: centroids, convergence and when it breaks",
    "date": "2026-05-11",
    "series": "Production RAG",
    "part": 8
  },
  {
    "slug": "clustering-compression-not-classification",
    "title": "Clustering is a compression decision, not classification",
    "date": "2026-04-28",
    "series": "Production RAG",
    "part": 7
  },
  {
    "slug": "rag-observability-monitoring-production",
    "title": "Observability for RAG: Tracing, Latency and Hallucination Monitoring",
    "date": "2026-04-20",
    "series": "Production RAG",
    "part": 6
  },
  {
    "slug": "multi-agent-rag-orchestration",
    "title": "Agentic RAG: Complete Systems Guide from Architecture to Production",
    "date": "2026-04-15",
    "series": "Production RAG",
    "part": 5
  },
  {
    "slug": "rag-page-indexing-chunking",
    "title": "Chunking Strategies for RAG: Why Page-Level Indexing Changes Everything",
    "date": "2026-03-30",
    "series": "Production RAG",
    "part": 4
  },
  {
    "slug": "graphrag-vs-lazygraphrag-local-vs-global-rag",
    "title": "GraphRAG vs LazyGraphRAG: Choosing the Right Strategy for Local and Global Questions",
    "date": "2026-03-22",
    "series": "Production RAG",
    "part": 3
  },
  {
    "slug": "rag-deployment-testing-monitoring",
    "title": "From Prototype to Production: Deploying, Testing & Monitoring RAG",
    "date": "2026-03-15",
    "series": "Production RAG",
    "part": 2
  },
  {
    "slug": "production-rag-architecture",
    "title": "Building Production-Ready RAG: The Architecture Nobody Talks About",
    "date": "2026-03-08",
    "series": "Production RAG",
    "part": 1
  },
  {
    "slug": "barcode-scanner-tinyml",
    "title": "TinyML Barcode Detection: From Keras to Microcontroller",
    "date": "2026-03-08",
    "series": "TinyML on microcontrollers",
    "part": 2
  },
  {
    "slug": "tinyml-face-verification",
    "title": "TinyML Face Verification on Arduino with LiteRT",
    "date": "2026-03-08",
    "series": "TinyML on microcontrollers",
    "part": 1
  },
  {
    "slug": "signaldock-mqtt-iot",
    "title": "SignalDock: Containerised MQTT Messaging with Docker",
    "date": "2026-03-08",
    "series": null,
    "part": null
  },
  {
    "slug": "nifty50-stock-prediction",
    "title": "NIFTY 50 Stock Price Prediction: ARIMA vs LSTM",
    "date": "2026-03-08",
    "series": null,
    "part": null
  },
  {
    "slug": "python-data-analysis",
    "title": "Python Data Analysis: EDA, Visualisation & Statistical Inference",
    "date": "2026-03-08",
    "series": null,
    "part": null
  },
  {
    "slug": "angular-spa-routing",
    "title": "Angular SPA Routing: Lazy Loading, Guards & Child Routes",
    "date": "2026-03-08",
    "series": null,
    "part": null
  }
];
