/* Point-cloud shaders (GLSL ES 1.00). uLight is 0 on the dark theme and 1 on the light theme: the
   colour uniforms already carry the theme's palette, uLight only adjusts the few places where the
   dark version leans on additive brightness (the >1 colour multipliers, the funnel highlight, alpha). */
export const VERT = [
'attribute vec3 posB; attribute vec3 posS; attribute float tagA; attribute float tagB; attribute float rnd;',
'uniform float uDustDim,uMix,uBoot,uTime,uVel,uPx,uRad,uOn,uOpen,uGR,uFun,uWarp,uShake,uMaskX,uMaskA,uHole,uCamZ,uHelixH;',
'uniform vec3 uMouse,uHoleC; uniform vec4 uRip,uPart; uniform vec2 uFunT,uFunS; uniform vec3 uMouseW;',
'varying float vTag; varying float vHot; varying float vA; varying float vP; varying float vFun; varying float vG; varying float vOpen; varying float vFade; varying float vPart;',
'void main(){',
'  // Two beats, in order: the whole shape dissolves (uMix 0 -> .5, every particle at once), then the next shape forms (.5 -> 1).',
'  // Each particle swaps A for B somewhere in the widest part of the scatter, so nothing visibly travels as a rigid shape.',
'  float sw=clamp((uMix-.35+(rnd-.5)*.2)/.3,0.,1.); float m=sw*sw*(3.-2.*sw);',
'  vec3 p=mix(position,posB,m);',
'  float tg=mix(tagA,tagB,step(.5,m));',
'  float mid=pow(sin(3.14159265*uMix),2.2); float t=uTime;',   // global spread: starts gently, fully scattered halfway, gathers back the same way
'  float isDust=step(11.5,tg)*step(tg,12.5); p+=vec3(sin(t*.3+rnd*47.),cos(t*.26+rnd*31.),sin(t*.22+rnd*23.))*(isDust*7.+mid*(150.+rnd*240.));',
'  float e=clamp(uBoot*1.6-rnd*.6,0.,1.); e=1.-pow(1.-e,3.);',
'  p=mix(posS,p,e);',
'  float pulse=1.; float glow=0.;',
'  if((tg>7.5&&tg<11.5)||(tg>12.5&&tg<13.5)){ float sp=(tg<8.5)?t*.09:t*.2; float cs=cos(sp), sn=sin(sp); p.xz=vec2(p.x*cs+p.z*sn,-p.x*sn+p.z*cs); }',
'  if((tg>8.5&&tg<11.5)||(tg>12.5&&tg<13.5)) p.xz*=1.+sin(t*1.6+p.y*.028)*.07;',
'  float fadeY=1.; float smokeShrink=1.;',
'  if((tg>8.5&&tg<11.5)||(tg>12.5&&tg<13.5)) fadeY=1.-smoothstep(uHelixH*.42,uHelixH*.64,abs(p.y));',
'  if(tg>13.5&&tg<14.5){',
'    float spd=.028+fract(rnd*7.13)*.024;',
'    float life=fract(t*spd+rnd*17.);',
'    float ease=1.-pow(1.-life,2.3);',
'    vec2 rdir=normalize(p.xz+vec2(.0001)); vec2 perp=vec2(-rdir.y,rdir.x);',
'    float reach=.26+fract(rnd*5.31)*.2;',
'    float curl=sin(life*5.2+rnd*20.)*.6+sin(life*2.1+rnd*11.)*.35;',
'    p.xz+=rdir*ease*uHelixH*reach+perp*curl*ease*uHelixH*.13;',
'    p.y+=ease*uHelixH*(.2+fract(rnd*3.7)*.14)+sin(life*6.+rnd*6.28)*uHelixH*.035;',
'    fadeY=smoothstep(0.,.16,life)*(1.-smoothstep(.42,1.,life));',
'    smokeShrink=(1.+ease*.7)*(1.-smoothstep(.6,1.,life));',
'  }',
'  if(tg>12.5&&tg<13.5) pulse=.7+.3*sin(t*3.+rnd*20.);',
'  if(tg>1.5&&tg<2.5) pulse=.6+.4*sin(t*2.+rnd*30.);',
'  if(tg>2.5&&tg<3.5) p.y+=sin(p.x*.022+t*1.8+rnd*2.)*6.;',
'  if(tg>3.5&&tg<4.5) p.y+=sin(p.x*.017+t*1.1+rnd*4.)*22.+sin(p.z*.024-t*.9+rnd*3.)*14.;',
'  if(tg>4.5&&tg<5.5) pulse=.6+.4*(.5+.5*sin(t*5.));',
'  if(tg>5.5&&tg<6.5){ float idx=(tg-6.)*10.; pulse=pow(max(0.,sin(t*3.-idx*1.2)),3.); }',
'  vec3 inner=uMouse*(1.-.55*uOpen);',
'  if(tg>6.5&&tg<7.5){',
'    float di=distance(p,inner); pulse=uOpen*(1.-smoothstep(0.,uGR*.6,di));',
'    pulse+=uHole*(1.-smoothstep(0.,uGR*.13,distance(p,uHoleC*.65)))*.9;',
'    float a=t*1.3+rnd*6.28; p.xy+=vec2(cos(a),sin(a))*5.*(uOpen+uHole);',
'  } else if(uHole>.001){',
'    vec3 dm=p-uHoleC; float dd=length(dm); float fo=(1.-smoothstep(0.,uGR*.13,dd))*uHole;',
'    p+=normalize(dm+vec3(.001))*fo*uGR*.16; pulse*=(1.-fo*.92); glow=fo;',
'  }',
'  p.y+=uVel*(rnd-.5)*190.; p.x+=uVel*(fract(rnd*7.)-.5)*90.; p.z+=abs(uVel)*rnd*110.;',
'  float age=t-uRip.z;',
'  if(age>0.&&age<3.){ vec2 dd2=p.xy-uRip.xy; float d=length(dd2); float w=sin(d*.035-age*8.)*exp(-age*1.5)*exp(-d*.0018)*uRip.w; p.z+=w*34.; p.xy+=normalize(dd2+vec2(.001))*w*8.; }',
'  // Cursor repel: a true small SPHERE around the cursor point, measured in WORLD space (the helix, planet and globe are',
'  // moved and turned, so local coordinates would skew it). uMouseW is the cursor on the z=0 plane, or on the front',
'  // surface of the globe/planet when it is over one. Push is radial in 3D, then back into local space (rotation transpose).',
'  vec4 wpr=modelMatrix*vec4(p,1.);',
'  vec3 d3=wpr.xyz-uMouseW; float dq=length(d3); float f=(1.-smoothstep(0.,uRad,dq))*uOn;',
'  vec3 rmv=normalize(d3+vec3(.001))*f*f*38.+vec3(0.,0.,f*10.);',
'  p+=vec3(dot(modelMatrix[0].xyz,rmv),dot(modelMatrix[1].xyz,rmv),dot(modelMatrix[2].xyz,rmv));',
'  // Experience scene: each employer\'s thin outline (tags 20..23) lights up while its role is selected. uPart = (previous, current, crossfade, scene weight).',
'  float pg=0.;',
'  if(tg>19.5){ float pid=tg-20.; pg=(abs(pid-uPart.x)<.5?1.-uPart.z:0.)+(abs(pid-uPart.y)<.5?uPart.z:0.); pg*=uPart.w; pulse*=1.+pg*.3*sin(t*4.+rnd*20.); }',
'  vec3 wp0=(modelMatrix*vec4(p,1.)).xyz; vec2 w2=wp0.xy;',
'  float distT=clamp(length(w2-uFunT)/1500.,0.,1.);',
'  float thresh=rnd*.35+distT*.65;',
'  float fp=clamp(uFun*2.1-thresh*1.1,0.,1.); fp=fp*fp*fp*(fp*(fp*6.-15.)+10.);',
'  if(fp>0.){',
'    vec2 tgt=uFunT+(vec2(fract(rnd*37.1),fract(rnd*91.7))-.5)*uFunS*(1.-fp*.6);',
'    vec3 wd=vec3(tgt,0.)-wp0; vec2 perp=normalize(vec2(-wd.y,wd.x)+vec2(.001));',
'    float wob=sin(fp*3.14159)*(1.-fp)*(rnd-.5)*90.;',
'    vec3 wmv=vec3(wd.xy*fp+perp*wob,wd.z*fp)+vec3(sin(t*40.+rnd*20.),cos(t*37.+rnd*17.),0.)*uShake*fp*(1.-fp)*3.;',
'    p+=vec3(dot(modelMatrix[0].xyz,wmv),dot(modelMatrix[1].xyz,wmv),dot(modelMatrix[2].xyz,wmv));',
'  }',
'  if(uWarp>0.){',
'    vec4 wq=modelMatrix*vec4(p,1.);',
'    vec3 wo=vec3(normalize(wq.xy-uFunT+vec2(.001))*uWarp*(500.+rnd*1600.),uWarp*rnd*400.);',
'    p+=vec3(dot(modelMatrix[0].xyz,wo),dot(modelMatrix[1].xyz,wo),dot(modelMatrix[2].xyz,wo)); pulse*=(1.-uWarp);',
'  }',
'  vec4 wp=modelMatrix*vec4(p,1.);',
'  pulse*=1.-uDustDim*isDust;',   // quieter dust on the light theme so the shapes stand out
'  float mk=1.-uMaskA*(1.-smoothstep(uMaskX-140.,uMaskX+80.,wp.x)); mk=mix(mk,1.,fp);',
'  vTag=tg; vHot=f; vG=glow; vFun=fp; vP=pulse*mk; vOpen=uOpen; vFade=fadeY; vPart=pg;',
'  vec4 mv=modelViewMatrix*vec4(p,1.);',
'  gl_Position=projectionMatrix*mv;',
'  float boost=1.+f*1.1+fp*.6+pg*.9;',
'  if(tg>1.5&&tg<2.5) boost+=.4;',
'  if(tg>4.5&&tg<6.5) boost+=1.7*pulse;',
'  if(tg>3.5&&tg<4.5) boost+=.6;',
'  if(tg>6.5&&tg<7.5) boost+=1.2*pulse;',
'  if(tg>12.5&&tg<13.5) boost+=2.2*pulse;',
'  gl_PointSize=uPx*(.8+rnd*.9)*boost*smokeShrink*(1.-uDustDim*isDust*.5)*(1400./-mv.z);',
'  vA=.5+.5*rnd;',
'}'].join('\n');
export const FRAG = [
'precision mediump float;',
'uniform vec3 cIce,cVio,cAmb,cWat,cCya,cBer; uniform float uLight,uAlphaK;',
'varying float vTag; varying float vHot; varying float vA; varying float vP; varying float vFun; varying float vG; varying float vOpen; varying float vFade; varying float vPart;',
'void main(){ vec2 c=gl_PointCoord-.5; float d=length(c); if(d>.5) discard;',
'  float a=smoothstep(.5,.0,d);',
'  vec3 col=cIce;',
'  if(vTag>.5&&vTag<1.5) col=cVio; else if(vTag>1.5&&vTag<2.5) col=cAmb; else if(vTag>2.5&&vTag<3.5) col=cWat; else if(vTag>4.5&&vTag<6.5) col=cBer*mix(1.25,1.,uLight); else if(vTag>3.5&&vTag<4.5) col=mix(cIce,cWat,.55); else if(vTag>6.5&&vTag<7.5) col=cCya; else if(vTag>9.5&&vTag<10.5) col=cVio; else if(vTag>12.5&&vTag<13.5) col=cAmb*mix(2.4,1.1,uLight); else if(vTag>13.5&&vTag<14.5) col=mix(cIce,cCya,.5); else if(vTag>19.5) col=mix(cIce,cBer*mix(1.3,1.,uLight),vPart);',
'  vec3 hot=mix(cAmb,cCya,clamp(vOpen*1.6,0.,1.));',
'  col=mix(col,hot,clamp(vHot*1.5,0.,1.)); col=mix(col,cCya,clamp(vG*1.3,0.,1.)); col=mix(col,mix(vec3(.86,.88,1.),vec3(.22,.25,.80),uLight),vFun*.85);',
'  float al=a*vA*(.8+vHot*.7+vFun*.6)*vP*vFade*(1.+vPart*1.4);',
'  gl_FragColor=vec4(col,mix(al,min(1.,al*uAlphaK),uLight)); }'].join('\n');
